### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by indiv0** [DBDU/union#4]
This describes the current plan for the project:

# The Core Bot

1. [x] Develop a minimal bot with the following:
    * [x] cog loading support (#5, #26)
    * [x] core cog for admin functionality (#5, #26)

# Frontend

1. [ ] Setup a React-based skeleton for the webpage

# Deployment Backend

1. [ ] Containerize the bot
2. [ ] Define a way to auto-deploy an containerized instance of the bot:
    * [ ] Load in configuration as part of the process
    * [ ] Hardcode admin IDs as part of the process

# Management Backend

1. [ ] Define a database schema for storing information about active bot instances
2. [ ] Add ability to control a bot instance's access to cogs
3. [ ] Develop a payment system

**Comment by Vexs** [comment]
For the DB we could use fuyu's ORM- of importance to me is that basically we can put arbitrary stuff in, and pull it out with ease. Should be a attribute of the bot, perhaps dict-structed eg, `bot.settings[serverid][logchannel]` would be a nice way to be able to get at stuff.

**Comment by indiv0** [comment]
I'm OK with almost any ORM, as long as we actually use an ORM. As for which relational DB to use, my vote is for (in no particular order): PostgreSQL, MariaDB, SQLite.

**Comment by indiv0** [comment]
I've made a 1.0.0 milestone for the project. We'll file any issues that relate to getting the bot/framework to a working state under that. Any issues outside the 1.0.0 milestone should not be worked on for now.
